name: Build Executable with PyInstaller

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner to build a .exe file

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executable with PyInstaller
        run: pyinstaller --onefile assetsBrowser.py --icon .\lambda.ico --add-data .\icons/*;icons

      - name: Archive the build artifact
        uses: actions/upload-artifact@v3
        with:
          name: executable
          path: dist/assetsBrowser.exe  # Adjust to match the output executable name

